### ISSUE TITLE
"Could not connect to server" error after running :ChatterStart

### ISSUE THREAD

**Issue by waikoo** [Dan7h3x/Chatter.nvim#2]
Unfortunately I get an error when I run `:ChatterStart`:

```bash
Chatter is already set up
Error executing luv callback:
....local/share/nvim/lazy/plenary.nvim/lua/plenary/curl.lua:300: get http://localhost:8888/api/tags - curl error exit_code=7 stderr={ "curl: (7) Failed to connect to localhost port 8888 after 0 ms: Could not connect to server" }
stack traceback:
	[C]: in function 'error'
	....local/share/nvim/lazy/plenary.nvim/lua/plenary/curl.lua:300: in function '_user_on_exit'
	.../.local/share/nvim/lazy/plenary.nvim/lua/plenary/job.lua:241: in function '_shutdown'
	.../.local/share/nvim/lazy/plenary.nvim/lua/plenary/job.lua:48: in function <.../.local/share/nvim/lazy/plenary.nvim/lua/plenary/job.lua:39>
```

I don't know for sure if it relates but when I run `ollama serve` directly in a terminal, the port I get is `:11434`. So I tried changing that line from the setup:

```lua
offline_api_url = os.getenv("OLLAMA_HOST") or "http://localhost:8888",
```

 from `8888` to `11434` but the error message is the same.
 
 I also tried to run `ollama serve` directly in the terminal, and then run `:ChatterStart` but the error message is yet again the same.
 
 Do you know what the issue is?
 
 Great idea for a plugin btw!!!

**Comment by Dan7h3x** [comment]
Can you first check for running server of ollama?

Then set a variable OLAMMA_HOST in your system and the try with just the ChatterStart?

**Comment by waikoo** [comment]
I set the variable, ran `ollama serve` in a separate terminal, and that way it's working, I can even select which model to run after refreshing with ctrl + r, great! Thanks a lot!!!
