### ISSUE TITLE
What's the proper syntax for specifying the models?

### ISSUE THREAD

**Issue by waikoo** [Dan7h3x/Chatter.nvim#3]
I tried just off the top of my head:

```lua
models = { llama1b = "llama3.2:1b", llama3b = "llama3.2:3b" },
```

but (despite getting the error from #2) when I run `:ChatterToggle` I get:
```
#Model: Not Selected
```

How do I select it / initialize the models? Thanks.

**Comment by Dan7h3x** [comment]
Use the ChatterStart instead of ChatterToggle for automatic model start and selection

**Comment by waikoo** [comment]
Got it, thanks!
